language: python
python:
    - 2.6
    - 2.7
env:
    - BUILDENV=lucid
    - BUILDENV=precise
    - BUILDENV=latest
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qf python-libxml2
    - python -c 'import libxml2' || .travis/link-libxml2
install:
    - pip install --use-mirrors -r .travis/requirements-$BUILDENV.txt
script:
    - trial scrapy scrapyd
